spring:
  application:
    name: forum
  datasource:
    url: jdbc:h2:mem:forum
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create  # Garante que o Hibernate crie as tabelas
    defer-datasource-initialization: true  # <- ESSENCIAL PARA FUNCIONAR

  sql:
    init:
      mode: always  # Garante que o data.sql seja executado

  h2:
    console:
      enabled: true
      path: /h2-console