spring:
  application:
    name: forum

  datasource:
    url: jdbc:h2:mem:forum;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true
