spring:
  application:
    name: forum
  datasource:
    url: jdbc:h2:mem:forum;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true
jwt:
  # 32 bytes (256 bits) em Base64 como exemplo (NÃO usar em produção):
  secret: "uL9K4X2i1e2tYZH7mGcvjR1o9D0YfY2A9BzKc4gT1nQ="
  expiration: 360000
